ldap:
  host: "localhost"
  port: 389
  use_ssl: false
  insecure_skip_verify: false
  bind_dn: "cn=admin,dc=example,dc=org"
  base_dn: "dc=example,dc=org"
  attributes:
    email: mail
grafana:
  url: "http://localhost:3000"