ldap:
  host: "ldap://localhost:389"
  bind_dn: "cn=admin,dc=example,dc=org"
  base_dn: "dc=example,dc=org"
  server_attributes:
    email: mail
grafana:
  url: "http://localhost:3000"
sync:
  enabled: false
  schedule: "* * * * *"
mapping:
  - org_id: 1
    teams:
      - name: foo
        admins:
          user_filter: "(objectClass=inetOrgPerson)"
        memers:
          user_filter: "(objectClass=inetOrgPerson)"
  # - org_id: 2
  #   teams:
  #     - name: just bob
  #       admins:
  #         user_filter: "(&(objectClass=inetOrgPerson)(uid=bob))"