[[servers]]
host = "ldap"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=admin,dc=example,dc=org"
bind_password = "admin"
search_filter = "(uid=%s)"
search_base_dns = ["ou=users,dc=example,dc=org"]

group_search_filter = "(&(objectClass=groupOfNames)(member=%s))"
group_search_base_dns = ["ou=groups,dc=example,dc=org"]

[servers.attributes]
member_of = "memberOf"
email = "mail"
name = "cn"
surname = "sn"
username = "uid"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Admin"